Change kubectl wait to the other version
kubectl wait gives an error if there is no pod with the name we are waiting. So I am reverting this change.

diff --git a/.github/workflows/hz-dockerhub-release.yml b/.github/workflows/hz-dockerhub-release.yml
--- a/.github/workflows/hz-dockerhub-release.yml
+++ b/.github/workflows/hz-dockerhub-release.yml
@@ -197,8 +197,21 @@ jobs:
           HZ_NAME=$(grep -m 1 -Po "name: \K.+" ./${OPERATOR_NAME}/hazelcast.yaml)
           
           #WAIT FOR hz-hazelcast-2 TO BE READY
-          kubectl wait --for=condition=Ready --timeout=150s pod/${HZ_NAME}-${NAME}-2 
-
+          for i in `seq 1 10`; do
+            if [[ $(kubectl get pods ${HZ_NAME}-${NAME}-2 -o 'jsonpath={..status.conditions[?(@.type=="Ready")].status}') != "True" ]]; then
+              echo "waiting for pod ${HZ_NAME}-${NAME}-2 to be ready..." && sleep 15
+              if [ "$i" = "10" ]; then
+                echo "${HZ_NAME}-${NAME}-2 pod failed to be ready!"
+                kubectl get pods
+                echo ""
+                kubectl logs ${HZ_NAME}-${NAME}-2
+                exit 1
+              fi
+            else
+              echo "hz-${NAME}-2 is ready!"
+              break
+            fi
+          done
 
           #WAIT FOR CLUSTER SIZE TO BE 3
           for i in `seq 1 5`; do
